name: Update package-lock.json

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        check-latest: true
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: Configure git and update package
      run: |
        npm update
        git add -f package.json package-lock.json
        if git commit -m "Update package"; then
          git push
