name: 'Aliyun OSS files upload'
description: 'A GitHub Action to upload files to an Alibaba Cloud OSS bucket'
author: 'frenchvandal'
branding:
  color: 'orange'
  icon: 'cloud'

inputs:
  bucket:
    description: 'OSS bucket name'
    required: true
  region:
    description: 'OSS Region ID'
    required: true
  accessKeyId:
    description: 'Access Key ID'
    required: true
  accessKeySecret:
    description: 'Access Key secret'
    required: true
  source:
    description: 'Source folder of files to upload, relative to current working directory'
    required: false
  pattern:
    description: 'Glob pattern for source folder'
    required: false

runs:
  using: 'node14'
  main: 'dist/index.js'
